import { assertEquals, assertThrows } from "assert";
import { label, newContext } from "../../context/mod.ts";
import { tokenLine } from "../../source-code/testing.ts";
import {
    programMemoryOrigin, programMemoryBytes, newState
} from "../../state/mod.ts";
import { translator } from "../translate.ts";
import { type Tests, description } from "./testing.ts";

const state = newState();
const translate = translator(state);

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "CALL", ["branch"]], [0x94, 0x0e, 0x00, 0x00]],
    [["", "JMP",  ["branch"]], [0x94, 0x0c, 0x00, 0x00]]
];

Deno.test("Direct Program Code Generation", () => {
    newContext();
    programMemoryOrigin(0);
    label("branch");
    programMemoryOrigin(3);
    state.pass.start(2);
    for (const test of tests) {
        const line = tokenLine(...test[0]);
        assertEquals(translate(line), test[1], description(test));
    }
});

Deno.test("A jump should not be beyond the end of program memory", () => {
    newContext();
    programMemoryOrigin(0);
    programMemoryBytes(0x2000);
    state.pass.start(2);
    assertThrows(
        () => { translate(tokenLine("", "JMP", ["0x1001"])); },
        RangeError,
        "Operand out of range: should be within program memory 0 - 0x1000 not 0x1001"
    );
});
