import { assertEquals } from "assert";
import { newContext } from "../../context/mod.ts";
import { tokenLine } from "../../source-code/testing.ts";
import { newState } from "../../state/mod.ts";
import { translator } from "../translate.ts";
import { type Tests, description } from "./testing.ts";

const state = newState();
const translate = translator(state);

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "IN",  ["R19", (53 + 0x20).toString()]], [0xb7, 0x35]],
    [["", "OUT", [(25 + 0x20).toString(), "R16"]], [0xbb, 0x09]]
];

Deno.test("IO Byte Code Generation", () => {
    newContext();
    state.pass.start(2);
    for (const test of tests) {
        const line = tokenLine(...test[0]);
        assertEquals(translate(line), test[1], description(test));
    }
});
