import { assertEquals, assertInstanceOf, assertThrows } from "assert";
import { tokenLine } from "../../source-code/testing.ts";
import { newState } from "../../state/mod.ts";
import { translator } from "../translate.ts";
import { type Tests, description } from "./testing.ts";
import { IOPortOutOfRange } from "../../errors/errors.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "IN",  ["R19", (53 + 0x20).toString()]], [0xb7, 0x35]],
    [["", "OUT", [(25 + 0x20).toString(), "R16"]], [0xbb, 0x09]]
];

Deno.test("IO Byte Code Generation", () => {
    const state = newState();
    const translate = translator(state);
    state.pass.start(2);
    state.device.choose("dummy", { "ramEnd": 123, "reducedCore": false });
    for (const test of tests) {
        const line = tokenLine(...test[0]);
        assertEquals(translate(line), test[1], description(test));
    }
});

Deno.test("Ports > 5F get a nice hint about alternative instructions", () => {
    const state = newState();
    const translate = translator(state);
    state.device.choose("dummy", { "ramEnd": 123, "reducedCore": false });
    state.pass.start(2);
    const line = tokenLine("", "IN", ["R19", "0x60"])
    assertThrows(
        () => { translate(line); },
        IOPortOutOfRange
    )
    try {
        translate(line);
    } catch (error) {
        assertInstanceOf(error, IOPortOutOfRange);
        assertEquals(
            error.hint,
            "maybe you could try using LDS instead of IN to access data space beyond the usual IO area"
        );
    }
});
