import { assertEquals, assertThrows } from "assert";
import { chooseDevice, label } from "../../context/mod.ts";
import { blankSlate } from "../../coupling/coupling.ts";
import { translate } from "../translate.ts";
import {
    programMemoryOrigin, programMemoryStep, startPass
} from "../../state/mod.ts";
import { tokenLine } from "../../source-code/testing.ts";
import { type Tests, description } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "RCALL", ["back"   ]], [0xdf, 0xfc]],
    [["", "RJMP",  ["back"   ]], [0xcf, 0xfb]],
    [["", "RCALL", ["forward"]], [0xd0, 0x04]],
    [["", "RJMP",  ["forward"]], [0xc0, 0x03]]
];

Deno.test("Relative Program Code Generation", () => {
    blankSlate();
    chooseDevice("dummy", { "programEnd": 16 * 1024 });
    startPass(2);
    label("back");
    programMemoryOrigin(10);
    label("forward");
    programMemoryOrigin(3);
    for (const test of tests) {
        const line = tokenLine(...test[0]);
        assertEquals(translate(line), test[1], description(test));
        programMemoryStep(test[1]);
    }
});

Deno.test("Absolute address too high on RJMP instruction", () => {
    blankSlate();
    chooseDevice("dummy", { "programEnd": 16 * 1024 });
    startPass(2);
    assertThrows(
        () => translate(tokenLine("", "RJMP", ["0x1111"])),
        RangeError,
        "Operand out of range: should be relative jump to 12 bit range (-2048 - 2047) not 0x1111"
    );
});

Deno.test("Absolute address too low on RCALL instruction", () => {
    blankSlate();
    chooseDevice("dummy", { "programEnd": 16 * 1024 });
    startPass(2);
    programMemoryOrigin(0x2000);
    assertThrows(
        () => translate(tokenLine("", "RCALL", ["0x500"])),
        RangeError,
        "Operand out of range: should be relative jump to 12 bit range (-2048 - 2047) not 0x500"
    );
});
