import { assertEquals } from "assert";
import { tokenLine } from "../../source-code/testing.ts";
import { newState } from "../../state/mod.ts";
import { translator } from "../translate.ts";
import { type Tests, description } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "MOVW", ["R0", "R30"]], [0x01, 0x0f]]
];

Deno.test("Word Direct Code Generation", () => {
    const state = newState();
    const translate = translator(state);
    state.pass.start(2);
    state.device.choose("dummy", { "reducedCore": false });
    for (const test of tests) {
        const line = tokenLine(...test[0]);
        assertEquals(translate(line), test[1], description(test));
    }
});
