#!/bin/bash

# cSpell:words deno biomejs

export DENO_DIR="$(pwd)/_deno"
mkdir -p "${DENO_DIR}"

TASK="${1:-run}"
case $TASK in
specs)
    deno run -A ./build/instruction-sets/get-gnu-specs.ts
    ;;
run)
    deno run -A ./src/aaa.ts
    ;;
check)
    deno test --allow-read
    deno check -q $(find -name \*.ts | grep -v -e ./_deno/)
    deno lint
    deno run -A npm:@biomejs/biome check --javascript-formatter-enabled=false
    ;;
biome)
    deno run -A npm:@biomejs/biome check
    ;;
build)
    deno run -A ./build/definitions.ts
    ;;
*)
    echo "./run [check|biome|run|build]"
    exit 1
    ;;
esac
