#!/bin/bash

# cSpell:words deno biomejs

export DENO_DIR="$(pwd)/_deno"
mkdir -p "${DENO_DIR}"

TASK="${1:-run}"
case $TASK in
run)
    deno run -A ./src/input/cli.ts
    ;;
check)
    deno test --allow-read
    deno check -q $(find -name \*.ts | grep -v -e ./_deno/)
    deno lint
    deno run -A npm:@biomejs/biome check --javascript-formatter-enabled=false
    ;;
biome)
    deno run -A npm:@biomejs/biome check
    ;;
*)
    echo "./run [check|biome|run]"
    exit 1
    ;;
esac
