unsupportedInstructions = [
    "multiply", "readModifyWrite", "DES", "FlashMore128", "FlashMore8", "SPM.Z+"
]

reducedCore = false

# Power Reduction Register --------------------------------------- IO Address 00
PRR = 0x20

# Power Reduction Timer/Counter1
PRTIM1 = 0x03

# Power Reduction Timer/Counter0
PRTIM0 = 0x02

# Power Reduction USI
PRUSI = 0x01

# Power Reduction ADC
PRADC = 0x00

# Digital Input Disable 0 ---------------------------------------- IO Address 01
DIDR0 = 0x21

ADC7D = 0x07
ADC6D = 0x06
ADC5D = 0x05
ADC4D = 0x04
ADC3D = 0x03
ADC2D = 0x02
ADC1D = 0x01
ADC0D = 0x00

# ADC Control and Status B --------------------------------------- IO Address 03
ADCSRB = 0x23

# Bipolar Input Mode
BIN = 0x07

# Analog Comparator Multiplexer Enable
ACME = 0x06

# ADC Left Adjust Result
ADLAR = 0x04

# ADC Auto Trigger Source bit 2
ADTS2 = 0x02

# ADC Auto Trigger Source bit 1
ADTS1 = 0x01

# ADC Auto Trigger Source bit 0
ADTS0 = 0x00

# ADC Data Low --------------------------------------------------- IO Address 04
ADCL = 0x24

# ADC Data High -------------------------------------------------- IO Address 05
ADCH = 0x25

# ADC Control and Status A --------------------------------------- IO Address 06
ADCSRA = 0x26

# ADC Enable
ADEN = 0x07

# ADC Start Conversion
ADSC = 0x06

# ADC Auto Trigger Enable
ADATE = 0x05

# ADC Interrupt Flag
ADIF = 0x04

# ADC Interrupt Enable
ADIE = 0x03

# ADC Prescaler Select Bit 2
ADPS2 = 0x02

# ADC Prescaler Select Bit 1
ADPS1 = 0x01

# ADC Prescaler Select Bit 0
ADPS0 = 0x00

# ADC Multiplexer Selection -------------------------------------- IO Address 07
ADMUX = 0x27

# Reference Selection Bit 1
REFS1 = 0x07

# Reference Selection Bit 0
REFS0 = 0x06

# Analog Channel and Gain Selection Bit 5
MUX5 = 0x05

# Analog Channel and Gain Selection Bit 4
MUX4 = 0x04

# Analog Channel and Gain Selection Bit 3
MUX3 = 0x03

# Analog Channel and Gain Selection Bit 2
MUX2 = 0x02

# Analog Channel and Gain Selection Bit 1
MUX1 = 0x01

# Analog Channel and Gain Selection Bit 0
MUX0 = 0x00

# Analog Comparator Control/Status ------------------------------- IO Address 08
ACSR = 0x28

# Analog Comparator Disable
ACD = 0x07

# Analog Comparator Bandgap Select
ACBG = 0x06

# Analog Compare Output
ACO = 0x05

# Analog Comparator Interrupt Flag
ACI = 0x04

# Analog Comparator Interrupt Enable
ACIE = 0x03

# Analog Comparator Input Capture Enable
ACIC = 0x02

# Analog Comparator Interrupt Mode Select bit 1
ACIS1 = 0x01

# Analog Comparator Interrupt Mode Select bit 0
ACIS0 = 0x00

# Timer/Counter Interrupt Flag ----------------------------------- IO Address 0B
TIFR1 = 0x2B

# TC1 Input Capture Flag
ICF1 = 0x05

# TC1 Output Compare B Match Flag
OCF1B = 0x02

# TC1 Output Compare A Match Flag
OCF1A = 0x01

# TC1 Overflow Flag
TOV1 = 0x00

# Timer/Counter1 Interrupt Mask ---------------------------------- IO Address 0C
TIMSK1 = 0x2C

# TC1 Input Capture Interrupt Enable
ICIE1 = 0x05

# TC1 Output Compare B Match Interrupt Enable
OCIE1B = 0x02

# TC1 Output Compare A Match Interrupt Enable
OCIE1A = 0x01

# TC1 Overflow Interrupt Enable
TOIE1 = 0x00

# USI Control ---------------------------------------------------- IO Address 0D
USICR = 0x2D

# Start Condition Interrupt Enable
USISIE = 0x07

# Counter Overflow Interrupt Enable
USIOIE = 0x06

# USI Wire Mode Bit 1
USIWM1 = 0x05

# USI Wire Mode Bit 0
USIWM0 = 0x04

# USI Clock Source Select Bit 1
USICS1 = 0x03

# USI Clock Source Select Bit 0
USICS0 = 0x02

# Clock Strobe
USICLK = 0x01

# Toggle Clock Port Pin
USITC = 0x00

# USI Status ----------------------------------------------------- IO Address 0E
USISR = 0x2E

# Start Condition Interrupt Flag
USISIF = 0x07

# Counter Overflow Interrupt Flag
USIOIF = 0x06

# Stop Condition Flag
USIPF = 0x05

# Data Output Collision
USIDC = 0x04

# USI Counter Value Bit 3
USICNT3 = 0x03

# USI Counter Value Bit 2
USICNT2 = 0x02

# USI Counter Value Bit 1
USICNT1 = 0x01

# USI Counter Value Bit 0
USICNT0 = 0x00

# USI Data ------------------------------------------------------- IO Address 0F
USIDR = 0x2F

# USI Buffer ----------------------------------------------------- IO Address 10
USIBR = 0x30

# Pin Change Enable Mask 0 --------------------------------------- IO Address 12
PCMSK0 = 0x32

PCINT7 = 0x07
PCINT6 = 0x06
PCINT5 = 0x05
PCINT4 = 0x04
PCINT3 = 0x03
PCINT2 = 0x02
PCINT1 = 0x01
PCINT0 = 0x00

# General Purpose I/O Register 0 --------------------------------- IO Address 13
GPIOR0 = 0x33

# General Purpose I/O Register 1 --------------------------------- IO Address 14
GPIOR1 = 0x34

# General Purpose I/O Register 2 --------------------------------- IO Address 15
GPIOR2 = 0x35

# Port B Input --------------------------------------------------- IO Address 16
PINB = 0x36

PINB3 = 0x03
PINB2 = 0x02
PINB1 = 0x01
PINB0 = 0x00

# Port B DDR ----------------------------------------------------- IO Address 17
DDRB = 0x37

DDRB3 = 0x03
DDRB2 = 0x02
DDRB1 = 0x01
DDRB0 = 0x00

# Port B Output -------------------------------------------------- IO Address 18
PORTB = 0x38

PB3 = 0x03
PB2 = 0x02
PB1 = 0x01
PB0 = 0x00

# Port A Input --------------------------------------------------- IO Address 19
PINA = 0x39

PINA7 = 0x07
PINA6 = 0x06
PINA5 = 0x05
PINA4 = 0x04
PINA3 = 0x03
PINA2 = 0x02
PINA1 = 0x01
PINA0 = 0x00

# Port A DDR ----------------------------------------------------- IO Address 1A
DDRA = 0x3A

DDRA7 = 0x07
DDRA6 = 0x06
DDRA5 = 0x05
DDRA4 = 0x04
DDRA3 = 0x03
DDRA2 = 0x02
DDRA1 = 0x01
DDRA0 = 0x00

# Port A Output -------------------------------------------------- IO Address 1B
PORTA = 0x3B

PA7 = 0x07
PA6 = 0x06
PA5 = 0x05
PA4 = 0x04
PA3 = 0x03
PA2 = 0x02
PA1 = 0x01
PA0 = 0x00

# EEPROM Control ------------------------------------------------- IO Address 1C
EECR = 0x3C

# EEPROM Programming Mode Bit 1
EEPM1 = 0x05

# EEPROM Programming Mode Bit 0
EEPM0 = 0x04

# EEPROM Ready Interrupt Enable
EERIE = 0x03

# EEPROM Master Write Enable
EEMPE = 0x02

# EEPROM Master Write Enable
EEPE = 0x01

# EEPROM Ready Interrupt Enable
EERE = 0x00

# EEPROM Data ---------------------------------------------------- IO Address 1D
EEDR = 0x3D

# EEPROM Address Low --------------------------------------------- IO Address 1E
EEARL = 0x3E

# EEPROM Address High -------------------------------------------- IO Address 1F
EEARH = 0x3F

# Pin Change Enable Mask 1 --------------------------------------- IO Address 20
PCMSK1 = 0x40

PCINT11 = 0x03
PCINT10 = 0x02
PCINT9 = 0x01
PCINT8 = 0x00

# Watchdog Timer Control ----------------------------------------- IO Address 21
WDTCSR = 0x41

# Watchdog Timeout Interrupt Flag
WDIF = 0x07

# Watchdog Timeout Interrupt Enable
WDIE = 0x06

# Watchdog Timer Prescaler Bits
WDP3 = 0x05

# Watchdog Change Enable
WDCE = 0x04

# Watch Dog Enable
WDE = 0x03

# Watchdog Timer Prescaler Bits
WDP2 = 0x02

# Watchdog Timer Prescaler Bits
WDP1 = 0x01

# Watchdog Timer Prescaler Bits
WDP0 = 0x00

# TC1 Control C -------------------------------------------------- IO Address 22
TCCR1C = 0x42

# Force Output Compare for Channel A
FOC1A = 0x07

# Force Output Compare for Channel B
FOC1B = 0x06

# General Timer/Counter Control ---------------------------------- IO Address 23
GTCCR = 0x43

# Timer/Counter Synchronization Mode
TSM = 0x07

# Prescaler 0 Reset Timer/Counter n
PSR10 = 0x00

# TC1 Input Capture ---------------------------------------------- IO Address 24
ICR1L = 0x44

# TC1 Input Capture ---------------------------------------------- IO Address 25
ICR1H = 0x45

# Clock Prescale ------------------------------------------------- IO Address 26
CLKPR = 0x46

# Clock Prescaler Change Enable
CLKPCE = 0x07

# Clock Prescaler Select Bit 3
CLKPS3 = 0x03

# Clock Prescaler Select Bit 2
CLKPS2 = 0x02

# Clock Prescaler Select Bit 1
CLKPS1 = 0x01

# Clock Prescaler Select Bit 0
CLKPS0 = 0x00

# DebugWire Data Register ---------------------------------------- IO Address 27
DWDR = 0x47

# TC1 Output Compare B Low --------------------------------------- IO Address 28
OCR1BL = 0x48

# TC1 Output Compare B High -------------------------------------- IO Address 29
OCR1BH = 0x49

# TC1 Output Compare A Low --------------------------------------- IO Address 2A
OCR1AL = 0x4A

# TC1 Output Compare A High -------------------------------------- IO Address 2B
OCR1AH = 0x4B

# TC1 Low Byte --------------------------------------------------- IO Address 2C
TCNT1L = 0x4C

# TC1 High Byte -------------------------------------------------- IO Address 2D
TCNT1H = 0x4D

# TC1 Control B -------------------------------------------------- IO Address 2E
TCCR1B = 0x4E

# Input Capture 1 Noise Canceller
ICNC1 = 0x07

# Input Capture 1 Edge Select
ICES1 = 0x06

# Waveform Generation Mode Bits
WGM13 = 0x04

# (AKA CTC1) Waveform Generation Mode Bits
WGM12 = 0x03

# Clock Select1 Bit 2
CS12 = 0x02

# Clock Select1 Bit 1
CS11 = 0x01

# Clock Select1 Bit 0
CS10 = 0x00

# TC1 Control ---------------------------------------------------- IO Address 2F
TCCR1A = 0x4F

# Compare Output Mode 1A Bit 1
COM1A1 = 0x07

# Compare Output Mode 1A Bit 0
COM1A0 = 0x06

# Compare Output Mode 1B Bit 1
COM1B1 = 0x05

# Compare Output Mode 1B Bit 0
COM1B0 = 0x04

# Waveform Generation Mode Bit 1
WGM11 = 0x01

# Waveform Generation Mode Bit 0
WGM10 = 0x00

# Timer/Counter Control A ---------------------------------------- IO Address 30
TCCR0A = 0x50

# Compare Match Output A Mode Bit 1
COM0A1 = 0x07

# Compare Match Output A Mode Bit 0
COM0A0 = 0x06

# Compare Match Output B Mode Bit 1
COM0B1 = 0x05

# Compare Match Output B Mode Bit 0
COM0B0 = 0x04

# Waveform Generation Mode Bit 1
WGM01 = 0x01

# Waveform Generation Mode Bit 0
WGM00 = 0x00

# Oscillator Calibration Value ----------------------------------- IO Address 31
OSCCAL = 0x51

# Timer/Counter0 ------------------------------------------------- IO Address 32
TCNT0 = 0x52

# Timer/Counter Control ------------------------------------------ IO Address 33
TCCR0B = 0x53

# Force Output Compare for Channel A
FOC0A = 0x07

# Force Output Compare for Channel B
FOC0B = 0x06

# Waveform Generation Mode bit 2
WGM02 = 0x03

# Clock Select1 bit 2
CS02 = 0x02

# Clock Select1 bit 1
CS01 = 0x01

# Clock Select1 bit 0
CS00 = 0x00

# MCU Status ----------------------------------------------------- IO Address 34
MCUSR = 0x54

# Watchdog Reset
WDRF = 0x03

# Brown-out Reset
BORF = 0x02

# External Reset
EXTRF = 0x01

# Power-on reset
PORF = 0x00

# MCU Control ---------------------------------------------------- IO Address 35
MCUCR = 0x55

# BOD Sleep
BODS = 0x07

# Pull-up disable
PUD = 0x06

# Sleep enable
SE = 0x05

# Sleep Mode Select Bit 1
SM1 = 0x04

# Sleep Mode Select Bit 0
SM0 = 0x03

# BOD Sleep Enable
BODSE = 0x02

# Interrupt Sense Control 0 Bit 1
ISC01 = 0x01

# Interrupt Sense Control 0 Bit 0
ISC00 = 0x00

# TC0 Output Compare A ------------------------------------------- IO Address 36
OCR0A = 0x56

# Store Program Memory Control ----------------------------------- IO Address 37
SPMCSR = 0x57

# Clear temporary page buffer
CTPB = 0x04

# Read fuse and lock bits
RFLB = 0x03

# Page Write
PGWRT = 0x02

# Page Erase
PGERS = 0x01

# Store Program Memory Enable
SPMEN = 0x00

# TC0 Interrupt Flag Register ------------------------------------ IO Address 38
TIFR0 = 0x58

# Output Compare Flag B
OCF0B = 0x02

# Output Compare Flag A
OCF0A = 0x01

# Overflow Flag
TOV0 = 0x00

# TC0 Interrupt Mask --------------------------------------------- IO Address 39
TIMSK0 = 0x59

# Output Compare Match B Interrupt Enable
OCIE0B = 0x02

# Output Compare Match A Interrupt Enable
OCIE0A = 0x01

# Overflow Interrupt Enable
TOIE0 = 0x00

# General Interrupt Flag register -------------------------------- IO ADDRESS 3A
GIFR = 0x5A

# External Interrupt Flag 0
INTF0 = 0x06

# Pin Change Interrupt Flag 1
PCIF1 = 0x05

# Pin Change Interrupt Flag 0
PCIF0 = 0x04

# General Interrupt Mask Register -------------------------------- IO Address 3B
GIMSK = 0x5B

# External Interrupt Request 0 Enable
INT0 = 0x06

# Pin Change Interrupt Enable 1
PCIE1 = 0x05

# Pin Change Interrupt Enable 0
PCIE0 = 0x04

# TC0 Output Compare B ------------------------------------------- IO Address 3C
OCR0B = 0x5C

# Status Register ------------------------------------------------ IO Address 3F
SREG = 0x5F
