unsupportedInstructions = [
    "multiply", "readModifyWrite", "DES", "flashMore128", "flashMore8", "SPM.Z+"
]

reducedCore = false

# Digital Input Disable Register 1 ------------------------------ IO Address 01
DIDR = 0x21

# AIN1 Digital Input Disable
AIN1D = 0x01

# AIN0 Digital Input Disable
AIN0D = 0x00

# USART Baud Rate Register High Byte ----------------------------- IO Address 02
UBRRH = 0x22

# Analog Comparator Control/Status Reg --------------------------- IO Address 08
ACSR = 0x28

# Analog Comparator Disable
ACD = 0x07

# Analog Comparator Bandgap Select
ACBG = 0x06

# Analog Compare Output
ACO = 0x05

# Analog Comparator Interrupt Flag
ACI = 0x04

# Analog Comparator Interrupt Enable
ACIE = 0x03

# Analog Comparator Input Capture Enable
ACIC = 0x02

# Analog Comparator Interrupt Mode Toggle Bit 1
ACIS1 = 0x01

# Analog Comparator Interrupt Mode Toggle Bit 0
ACIS0 = 0x00

# USART Baud Rate Register Low Byte ------------------------------ IO Address 09
UBRRL = 0x29

# USART Control and Status Register B ---------------------------- IO Address 0A
UCSRB = 0x2A

# RX Complete Interrupt Enable
RXCIE = 0x07

# TX Complete Interrupt Enable
TXCIE = 0x06

# USART Data register Empty Interrupt Enable
UDRIE = 0x05

# Receiver Enable
RXEN = 0x04

# Transmitter Enable
TXEN = 0x03

# USART Data Size Bit 2
UCSZ2 = 0x02

# Receive Data Bit 8
RXB8 = 0x01

# Transmit Data Bit 8
TXB8 = 0x00

# USART Control and Status Register A ---------------------------- IO Address 0B
UCSRA = 0x2B

# USART Receive Complete
RXC = 0x07

# USART Transmit Complete
TXC = 0x06

# USART Data Register Empty
UDRE = 0x05

# Framing Error
FE = 0x04

# Data overRun
DOR = 0x03

# USART Parity Error
UPE = 0x02

# Double the USART Transmission Speed
U2X = 0x01

# Multi-processor Communication Mode
MPCM = 0x01

# USART I/O Data Register ---------------------------------------- IO Address 0C
UDR = 0x2C

# USI Control Register –------------------------------------------ IO Address 0D
USICR = 0x2D

# Start Condition Interrupt Enable
USISIE = 0x07

# Counter Overflow Interrupt Enable
USIOIE = 0x06

# Wire Mode - bit 1
USIWM1 = 0x05

# Wire Mode - bit 0
USIWM0 = 0x04

# Clock Source Select bit 1
USICS1 = 0x03

# Clock Source Select bit 0
USICS0 = 0x02

# Clock Strobe
USICLK = 0x01

# Clock Port Pin
USITC = 0x00

# USI Status Register –------------------------------------------- IO Address 0E
USISR = 0x2E

# Condition Interrupt Flag
USISIF = 0x07

# Overflow Interrupt Flag
USIOIF = 0x06

# Stop Condition Flag
USIPF = 0x05

# Output Collision
USIDC = 0x04

# Counter Value bit 3
USICNT3 = 0x03

# Counter Value bit 2
USICNT2 = 0x02

# Counter Value bit 1
USICNT1 = 0x01

# Counter Value bit 0
USICNT0 = 0x00

# USI Data Register –--------------------------------------------- IO Address 0F
USIDR = 0x2F

# Port D Input Pins Register ------------------------------------- IO Address 10
PIND = 0x30

PIND6 = 0x06
PIND5 = 0x05
PIND4 = 0x04
PIND3 = 0x03
PIND2 = 0x02
PIND1 = 0x01
PIND0 = 0x00

# Port D Data Direction Register --------------------------------- IO Address 11
DDRD = 0x31

DDRD6 = 0x06
DDRD5 = 0x05
DDRD4 = 0x04
DDRD3 = 0x03
DDRD2 = 0x02
DDRD1 = 0x01
DDRD0 = 0x00

# Port D Data Register ------------------------------------------- IO Address 12
PORTD = 0x32

PORTD6 = 0x06
PORTD5 = 0x05
PORTD4 = 0x04
PORTD3 = 0x03
PORTD2 = 0x02
PORTD1 = 0x01
PORTD0 = 0x00

# General Purpose I/O Register 0 --------------------------------- IO Address 13
GPIOR0 = 0x33

# General Purpose I/O Register 1 --------------------------------- IO Address 14
GPIOR1 = 0x34

# General Purpose I/O Register 2 --------------------------------- IO Address 15
GPIOR2 = 0x35

# Port B Input Pins Register ------------------------------------- IO Address 16
PINB = 0x36

PINB7 = 0x07
PINB6 = 0x06
PINB5 = 0x05
PINB4 = 0x04
PINB3 = 0x03
PINB2 = 0x02
PINB1 = 0x01
PINB0 = 0x00

# Port B Data Direction Register --------------------------------- IO Address 17
DDRB = 0x37

DDRB7 = 0x07
DDRB6 = 0x06
DDRB5 = 0x05
DDRB4 = 0x04
DDRB3 = 0x03
DDRB2 = 0x02
DDRB1 = 0x01
DDRB0 = 0x00

# Port B Data Register ------------------------------------------- IO Address 18
PORTB = 0x38

PORTB7 = 0x07
PORTB6 = 0x06
PORTB5 = 0x05
PORTB4 = 0x04
PORTB3 = 0x03
PORTB2 = 0x02
PORTB1 = 0x01
PORTB0 = 0x00

# Port A Input Pins Register ------------------------------------- IO Address 19
PINA = 0x39

PINA2 = 0x02
PINA1 = 0x01
PINA0 = 0x00

# Port A Data Direction Register --------------------------------- IO Address 1A
DDRA = 0x3A

DDRA2 = 0x02
DDRA1 = 0x01
DDRA0 = 0x00

# Port A Data Register ------------------------------------------- IO Address 1B
PORTA = 0x3B

PORTA2 = 0x02
PORTA1 = 0x01
PORTA0 = 0x00

# EEPROM Control Register ---------------------------------------- IO Address 1C
EECR = 0x3C

# EEPROM Programming Mode Bit 1
EEPM1 = 0x05

# EEPROM Programming Mode Bit 0
EEPM0 = 0x04

# EEProm Ready Interrupt Enable
EERIE = 0x03

# EEPROM Master Program (Write) Enable
EEMPE = 0x02

# EEPROM Program (Write) Enable
EEPE = 0x01

# EEPROM Read Enable
EERE = 0x00

# EEPROM Data Register ------------------------------------------- IO Address 1D
EEDR = 0x3D

# EEPROM Read/Write Access --------------------------------------- IO Address 1E
EEAR = 0x3E

# Watchdog Timer Control Register -------------------------------- IO Address 21
WDTCSR = 0x41

# Watchdog Timeout Interrupt Flag
WDIF = 0x07

# Watchdog Timeout Interrupt Enable
WDIE = 0x06

# Watchdog Timer Prescaler bit 3
WDP3 = 0x05

# Watchdog Change Enable
WDCE = 0x04

# Watch Dog Enable
WDE = 0x03

# Watchdog Timer Prescaler bit 2
WDP2 = 0x02

# Watchdog Timer Prescaler bit 1
WDP1 = 0x01

# Watchdog Timer Prescaler bit 0
WDP0 = 0x00

# TC1 Control Register C ----------------------------------------- IO Address 22
TCCR1C = 0x42

# Force Output Compare for Channel B
FOC1B = 0x07

# Force Output Compare for Channel A
FOC1A = 0x06

# General Timer Counter Control ---------------------------------- IO Address 23
GTCCR = 0x43

# Prescaler Reset Timer/Counter1 and Timer/Counter0
PSR10 = 0x00

# TC1 Input Capture Register Low Byte ---------------------------- IO Address 24
ICR1L = 0x44

# TC1 Input Capture Register High Byte --------------------------- IO Address 25
ICR1H = 0x45

# Clock Prescale Register ---------------------------------------- IO Address 26
CLKPR = 0x46

# Clock Prescaler Change Enable
CLKPCE = 0x07

# Clock Prescaler Select Bit 3
CLKPS3 = 0x03

# Clock Prescaler Select Bit 2
CLKPS2 = 0x02

# Clock Prescaler Select Bit 1
CLKPS1 = 0x01

# Clock Prescaler Select Bit 0
CLKPS0 = 0x00

# TC1 Compare Register B Low Byte -------------------------------- IO Address 28
OCR1BL = 0x48

# TC1 Compare Register B High Byte ------------------------------- IO Address 29
OCR1BH = 0x49

# TC1 Compare Register A Low Byte -------------------------------- IO Address 2A
OCR1AL = 0x4A

# TC1 Compare Register A High Byte ------------------------------- IO Address 2B
OCR1AH = 0x4B

# TC1 Counter Register Low Byte ---------------------------------- IO Address 2C
TCNT1L = 0x4C

# TC1 Counter Register High Byte --------------------------------- IO Address 2D
TCNT1H = 0x4D

# Timer/Counter1 Control Register B
TCCR1B = 0x4E

# Input Capture 1 Noise Canceller
ICNC1 = 0x07

# Input Capture 1 Edge Select
ICES1 = 0x06

# Waveform Generation 1 Mode Bit 3
WGM13 = 0x04

# Waveform Generation 1 Mode Bit 2
WGM12 = 0x03

# Clock Select 1 bit 2
CS12 = 0x02

# Clock Select 1 bit 1
CS11 = 0x01

# Clock Select 1 bit 0
CS10 = 0x00

# TC1 Control Register A ----------------------------------------- IO Address 2F
TCCR1A = 0x4F

# Compare Output Mode 1A, bit 1
COM1A1 = 0x07

# Compare Output Mode 1A, bit 0
COM1A0 = 0x06

# Compare Output Mode 1B, bit 1
COM1B1 = 0x05

# Compare Output Mode 1B, bit 0
COM1B0 = 0x04

# Pulse Width Modulator Select Bit 1
WGM11 = 0x01

# Pulse Width Modulator Select Bit 0
WGM10 = 0x00

# Timer/Counter Control Register A ------------------------------- IO Address 30
TCCR0A = 0x50

# Compare Match Output A Mode bit 1
COM0A1 = 0x07

# Compare Match Output A Mode bit 0
COM0A0 = 0x06

# Compare Match Output B Mode bit 1
COM0B1 = 0x05

# Compare Match Output B Mode bit 0
COM0B0 = 0x04

# Waveform Generation Mode bit 1
WGM01 = 0x01

# Waveform Generation Mode bit 0
WGM00 = 0x00

# Oscillator Calibration Register -------------------------------- IO Address 31
OSCCAL = 0x51

CAL6 = 0x06
CAL5 = 0x05
CAL4 = 0x04
CAL3 = 0x03
CAL2 = 0x02
CAL1 = 0x01
CAL0 = 0x00

# Timer/Counter0 ------------------------------------------------- IO Address 32
TCNT0 = 0x52

# Timer/Counter Control Register B ------------------------------- IO Address 33
TCCR0B = 0x53

# Force Output Compare A
FOC0A = 0x07

# Force Output Compare B
FOC0B = 0x06

# Waveform Generation Mode - see also TCCR0A
WGM02 = 0x03

# Clock Select 0 bit 2
CS02 = 0x02

# Clock Select 0 bit 1
CS01 = 0x01

# Clock Select 0 bit 0
CS00 = 0x00

# MCU Status register -------------------------------------------- IO Address 34
MCUSR = 0x54

# Watchdog Reset Flag
WDRF = 0x03

# Brown-out Reset Flag
BORF = 0x02

# External Reset Flag
EXTRF = 0x01

# Power-On Reset Flag
PORF = 0x00

# MCU Control Register ------------------------------------------- IO Address 35
MCUCR = 0x55

# Pull-up Disable
PUD = 0x07

# TC0 Output Compare Register A ---------------------------------- IO Address 36
OCR0A = 0x56

# Store Program Memory Control & Status -------------------------- IO Address 37
SPMCSR = 0x57

# Clear Temporary Page Buffer
CTPB = 0x04

# Read Fuse and Lock Bits
RFLB = 0x03

# Page Write
PGWRT = 0x02

# Page Erase
PGERS = 0x01

# Self Programming Enable
SELFPRGEN = 0x00

# Timer/Counter Interrupt Flag Register -------------------------- IO Address 38
TIFR = 0x58

# TC1 Overflow Flag
TOV1 = 0x07

# Output Compare Flag 1A
OCF1A = 0x06

# Output Compare Flag 1B
OCF1B = 0x05

# Input Capture Flag 1
ICF1 = 0x03

# TC0 Output Compare Flag 0B
OCF0B = 0x02

# TC0 Overflow Flag
TOV0 = 0x01

# TC0 Output Compare Flag 0A
OCF0A = 0x00

# Timer/Counter Interrupt Mask Register -------------------------- IO Address 39
TIMSK = 0x59

# TC1 Overflow Interrupt Enable
TOIE1 = 0x07

# TC1 Output CompareA Match Interrupt Enable
OCIE1A = 0x06

# TC1 Output CompareB Match Interrupt Enable
OCIE1B = 0x05

# TC1 Input Capture Interrupt Enable
ICIE1 = 0x03

# TC0 Output Compare Match B Interrupt Enable
OCIE0B = 0x02

# TC0 Overflow Interrupt Enable
TOIE0 = 0x01

# TC0 Output Compare Match A Interrupt Enable
OCIE0A = 0x00

# TC0 Output Compare Register ------------------------------------ IO Address 3C
OCR0B = 0x5C

# Stack Pointer -------------------------------------------------- IO Address 3D
SPL = 0x5D

# Processor status register -------------------------------------- IO Address 3F
SREG = 0x5F
