{
    "family": "attiny-x4",
    "spec": {
        "SPL": {
            "value": "5D",
            "description": "Stack Pointer ----------------------- IO Address 3D"
        },

        "SPH": {
            "value": "5E",
            "description": "Stack Pointer ----------------------- IO Address 3E"
        },

        "eepromEnd":          { "value": "00FF" },

        "programMemoryBytes": { "value": "0FFF" },

        "ioRegistersStart":   { "value": "0020" },

        "ioRegistersEnd":     { "value": "005F" },

        "ramStart":           { "value": "0060" },

        "ramEnd":             { "value": "015F" }
    }
}
