family = "attiny-x313"

[spec]

eepromEnd = 0x00FF

programMemoryBytes = 0x0FFF

ioRegistersStart = 0x20
ioRegistersEnd = 0x5F

ramStart = 0x60
ramEnd = 0x015F

# USART MSPIM Control/Status C ----------------------------------- IO Address 03
UCSRC = 0x23

# USART Mode Select bit 1
UMSEL1 = 0x07

# USART Mode Select bit 1
UMSEL0 = 0x06

# Data Order
UDORD = 0x02

# Clock Phase
UCPHA = 0x01

# Clock Polarity
UCPOL = 0x00

# Pin Change Mask Register 1 ------------------------------------- IO Address 04
PCMSK1 = 0x24

PCINT10 = 0x02
PCINT9 = 0x01
PCINT8 = 0x00

# Pin Change Mask Register 2 ------------------------------------- IO Address 05
PCMSK2 = 0x25

PCINT17 = 0x06
PCINT16 = 0x05
PCINT15 = 0x04
PCINT14 = 0x03
PCINT13 = 0x02
PCINT12 = 0x01
PCINT11 = 0x00

# Power Reduction Register --------------------------------------- IO Address 06
PRR = 0x26

# Power Reduction Timer/Counter1
PRTIM1 = 0x03

# Power Reduction Timer/Counter0
PRTIM0 = 0x02

# Power Reduction USI
PRUSI = 0x01

# Power Reduction USART
PRUSART = 0x00

# BOD control register ------------------------------------------- IO Address 07
BODCR = 0x27

# BOD Sleep
BODS = 0x01

# BOD Sleep Enable
BODSE = 0x00

# Pin Change Mask Register 0 ------------------------------------- IO Address 20
PCMSK0 = 0x40

PCINT7 = 0x07
PCINT6 = 0x06
PCINT5 = 0x05
PCINT4 = 0x04
PCINT3 = 0x03
PCINT2 = 0x02
PCINT1 = 0x01
PCINT0 = 0x00

# General Interrupt Flag ----------------------------------------- IO Address 3A
GIFR = 0x5A

# External Interrupt Flag 1
INTF1 = 0x07

# External Interrupt Flag 0
INTF0 = 0x06

# Pin Change Interrupt Flag 0
PCIF0 = 0x05

# Pin Change Interrupt Flag 2
PCIF2 = 0x04

# Pin Change Interrupt Flag 1
PCIF1 = 0x03

# General Interrupt Mask ----------------------------------------- IO Address 3B
GIMSK = 0x5B

# External Interrupt Request 1 Enable
INT1 = 0x07

# Interrupt Request 0 Enable
INT0 = 0x06

# Pin Change Interrupt Enable Bit 0
PCIE0 = 0x05

# Pin Change Interrupt Enable Bit 2
PCIE2 = 0x04

# Pin Change Interrupt Enable Bit 1
PCIE1 = 0x03
