family = "attiny-x4"

[spec]

eepromEnd = 0x01FF

programMemoryBytes = 0x1FFF

ioRegistersStart = 0x0020
ioRegistersEnd = 0x005F

ramStart = 0x0060
ramEnd = 0x025F

# Stack Pointer -------------------------------------------------- IO Address 3D
SPL = 0x5D

# Stack Pointer -------------------------------------------------- IO Address 3E
SPH = 0x5E
