{
    "family": "attiny-x313",
    "spec": {
        "UCSRC": {
            "value": "23",
            "description": "USART MSPIM Control/Status C -------- IO Address 03"
        },
        "UMSEL1": {
            "value": "7",
            "description": "USART Mode Select bit 1"
        },
        "UMSEL0": {
            "value": "6",
            "description": "USART Mode Select bit 1"
        },
        "UDORD": {
            "value": "2",
            "description": "Data Order"
        },
        "UCPHA": {
            "value": "1",
            "description": "Clock Phase"
        },
        "UCPOL": {
            "value": "0",
            "description": "Clock Polarity"
        },

        "PCMSK1": {
            "value": "24",
            "description": "Pin Change Mask Register 1 ---------- IO Address 04"
        },
        "PCINT10": {
            "value": "2"
        },
        "PCINT9": {
            "value": "1"
        },
        "PCINT8": {
            "value": "0"
        },

        "PCMSK2": {
            "value": "25",
            "description": "Pin Change Mask Register 2 ---------- IO Address 05"
        },
        "PCINT17": {
            "value": "6"
        },
        "PCINT16": {
            "value": "5"
        },
        "PCINT15": {
            "value": "4"
        },
        "PCINT14": {
            "value": "3"
        },
        "PCINT13": {
            "value": "2"
        },
        "PCINT12": {
            "value": "1"
        },
        "PCINT11": {
            "value": "0"
        },

        "PRR": {
            "value": "26",
            "description": "Power Reduction Register ------------ IO Address 06"
        },
        "PRTIM1": {
            "value": "3",
            "description": "Power Reduction Timer/Counter1"
        },
        "PRTIM0": {
            "value": "2",
            "description": "Power Reduction Timer/Counter0"
        },
        "PRUSI": {
            "value": "1",
            "description": "Power Reduction USI"
        },
        "PRUSART": {
            "value": "0",
            "description": "Power Reduction USART"
        },

        "BODCR": {
            "value": "27",
            "description": "BOD control register ---------------- IO Address 07"
        },
        "BODS": {
            "value": "1",
            "description": "BOD Sleep"
        },
        "BODSE": {
            "value": "0",
            "description": "BOD Sleep Enable"
        },

        "PCMSK0": {
            "value": "40",
            "description": "Pin Change Mask Register 0 ---------- IO Address 20"
        },
        "PCINT7": {
            "value": "7"
        },
        "PCINT6": {
            "value": "6"
        },
        "PCINT5": {
            "value": "5"
        },
        "PCINT4": {
            "value": "4"
        },
        "PCINT3": {
            "value": "3"
        },
        "PCINT2": {
            "value": "2"
        },
        "PCINT1": {
            "value": "1"
        },
        "PCINT0": {
            "value": "0"
        },

        "GIFR": {
            "value": "5A",
            "description": "General Interrupt Flag -------------- IO Address 3A"
        },
        "INTF1": {
            "value": "7",
            "description": "External Interrupt Flag 1"
        },
        "INTF0": {
            "value": "6",
            "description": "External Interrupt Flag 0"
        },
        "PCIF0": {
            "value": "5",
            "description": "Pin Change Interrupt Flag 0"
        },
        "PCIF2": {
            "value": "4",
            "description": "Pin Change Interrupt Flag 2"
        },
        "PCIF1": {
            "value": "3",
            "description": "Pin Change Interrupt Flag 1"
        },

        "GIMSK": {
            "value": "5B",
            "description": "General Interrupt Mask -------------- IO Address 3B"
        },
        "INT1": {
            "value": "7",
            "description": "External Interrupt Request 1 Enable"
        },
        "INT0": {
            "value": "6",
            "description": "Interrupt Request 0 Enable"
        },
        "PCIE0": {
            "value": "5",
            "description": "Pin Change Interrupt Enable Bit 0"
        },
        "PCIE2": {
            "value": "4",
            "description": "Pin Change Interrupt Enable Bit 2"
        },
        "PCIE1": {
            "value": "3",
            "description": "Pin Change Interrupt Enable Bit 1"
        },

        "eepromEnd":          { "value": "7F" },

        "programMemoryBytes": { "value": "07FF" },

        "ioRegistersStart":   { "value": "20" },

        "ioRegistersEnd":     { "value": "5F" },

        "ramStart":           { "value": "60" },

        "ramEnd":             { "value": "DF" }
    }
}
