family = "attiny-x4"

[spec]

eepromEnd = 0x007F

programMemoryBytes = 0x07FF

ioRegistersStart = 0x0020
ioRegistersEnd = 0x005F

ramStart = 0x0060
ramEnd = 0x00DF

# Stack Pointer -------------------------------------------------- IO Address 3D
SPL = 0x5D
