family = "attiny-x313"

[spec]

eepromEnd = 0x7F

programMemoryBytes = 0x07FF

ioRegistersStart = 0x20
ioRegistersEnd = 0x5F

ramStart = 0x60
ramEnd = 0xDF

# USART Control/Status Register C -------------------------------- IO Address 03
UCSRC = 0x23

# USART Mode Select (asynchronous / synchronous)
UMSEL = 0x06

# USART Parity Mode Bit 1
UPM1 = 0x05

# USART Parity Mode Bit 0
UPM0 = 0x04

# USART Stop bits
USBS = 0x03

# USART Data Size Bit 1
UCSZ1 = 0x02

# USART Data Size Bit 0
UCSZ0 = 0x01

# USART Clock Polarity
UCPOL = 0x00

# Pin Change Mask Register --------------------------------------- IO Address 20
PCMSK = 0x40

PCINT7 = 0x07
PCINT6 = 0x06
PCINT5 = 0x05
PCINT4 = 0x04
PCINT3 = 0x03
PCINT2 = 0x02
PCINT1 = 0x01
PCINT0 = 0x00

# External Interrupt Flag ---------------------------------------- IO Address 3A
EIFR = 0x5A

# External Interrupt Flag 1
INTF1 = 0x07

# External Interrupt Flag 0
INTF0 = 0x06

# Pin Change Interrupt Flag
PCIF = 0x05

# General Interrupt Mask ----------------------------------------- IO Address 3B
GIMSK = 0x5B

# External Interrupt Request 1 Enable
INT1 = 0x07

# Interrupt Request 0 Enable
INT0 = 0x06

# Pin Change Interrupt Enable
PCIE = 0x05
