import { newContext } from "../context/mod.ts";
import { generator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "LDS", ["R30", "1024"]], [0xE0, 0x91, 0x00, 0x04]],
    // TODO: LDS.RC
    [["", "STS", ["4096", "R8"]], [0x80, 0x92, 0x00, 0x10]],
    // TODO: STS.RC
];

testing(tests, generator(newContext(0)));