import { createOurContext } from "../context/mod.ts";
import { translator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["DES", ["15"]], [0x94, 0xfb]]
];

testing(tests, translator(createOurContext()));
