import { assertEquals } from "assert";
import { translator } from "../generate/mod.ts";
import { setPass } from "../operands/mod.ts";
import { type Tests, description} from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["DES", ["15"]], [0x94, 0xfb]]
];

Deno.test("DES Code Generation", () => {
    setPass(2);
    const translate = translator();
    for (const test of tests) {
        assertEquals(translate(test[0]), test[1], description(test));
    }
});
