import { assertEquals } from "assert";
import { newContext } from "../context/mod.ts";
import { generator, littleEndian } from "../generate/mod.ts";

const generate = generator(newContext(0));

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests = [
    ["BREAK", [0x98, 0x95]],
    ["NOP", [0, 0]],
    ["RET", [0x08, 0x95]],
    ["RETI", [0x18, 0x95]],
    ["SLEEP", [0x88, 0x95]],
    ["WDR", [0xa8, 0x95]],
    ["IJMP", [0x09, 0x94]],
    ["EIJMP", [0x19, 0x94]],
    ["ICALL", [0x09, 0x95]],
    ["EICALL", [0x19, 0x95]]
];

for (const test of tests) {
    const mnemonic = test[0] as string;
    Deno.test(`Basic code generation: ${mnemonic}`, () => {
        assertEquals(littleEndian(generate([mnemonic, [], [], 0])), test[1]);
    });
}
