import { createOurContext } from "../context/mod.ts";
import { generator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

const generate = generator(createOurContext());

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [
        ["", "LDD", ["R20", "Y+", "8"]],
        [0x48, 0x85]
    ],
    [
        ["", "LDD", ["R24", "Z+", "6"]],
        [0x86, 0x81]
    ],
    [
        ["", "STD", ["Y+", "9", "R6"]],
        [0x69, 0x86]
    ],
    [
        ["", "STD", ["Z+", "13", "R10"]],
        [0xa5, 0x86]
    ]
];

testing(tests, generate);
