import { assertEquals } from "assert";
import { translator } from "../generate/mod.ts";
import { operandConverter } from "../operands/mod.ts";
import { type Tests, description} from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["CBI",  [(30 + 0x20).toString(), "1"]], [0x98, 0xf1]],
    [["SBI",  [(28 + 0x20).toString(), "5"]], [0x9a, 0xe5]],
    [["SBIC", [(29 + 0x20).toString(), "4"]], [0x99, 0xec]],
    [["SBIS", [(30 + 0x20).toString(), "3"]], [0x9b, 0xf3]]
];

Deno.test("IO Bit Code Generation", () => {
    const translate = translator(operandConverter());
    for (const test of tests) {
        assertEquals(translate(test[0]), test[1], description(test));
    }
});
