import { newContext } from "../context/mod.ts";
import { generator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "IN", ["R19", "53"]], [0x35, 0xb7]],
    [["", "OUT", ["25", "R16"]], [0x09, 0xbb]],
];

testing(tests, generator(newContext(0)));
