import { createOurContext } from "../context/mod.ts";
import { translator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["CBI",  [(30 + 0x20).toString(), "1"]], [0x98, 0xf1]],
    [["SBI",  [(28 + 0x20).toString(), "5"]], [0x9a, 0xe5]],
    [["SBIC", [(29 + 0x20).toString(), "4"]], [0x99, 0xec]],
    [["SBIS", [(30 + 0x20).toString(), "3"]], [0x9b, 0xf3]]
];

testing(tests, translator(createOurContext()));
