import { assertEquals } from "assert";
import { newContext } from "../context/mod.ts";
import { translate } from "../generate/mod.ts";
import { startPass } from "../state/mod.ts";
import { tokenLine } from "../source-code/testing.ts";
import { type Tests, description } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "FMUL",   ["R16", "R23"]], [0x03, 0x0f]],
    [["", "FMULS",  ["R17", "R20"]], [0x03, 0x94]],
    [["", "FMULSU", ["R18", "R21"]], [0x03, 0xad]],
    [["", "MULS",   ["R16", "R31"]], [0x02, 0x0f]],
    [["", "MULSU",  ["R16", "R18"]], [0x03, 0x02]]
];

Deno.test("Multiply Code Generation", () => {
    newContext();
    startPass(2);
    for (const test of tests) {
        const line = tokenLine(...test[0]);
        assertEquals(translate(line), test[1], description(test));
    }
});
