import { assertEquals, assertThrows } from "assert";
import { littleEndian } from "../generate/mod.ts";
import { generator } from "../generate/mod.ts";
import { newContext } from "../context/mod.ts";
import { Instruction } from "../instruction/mod.ts";

const generate = generator(newContext(0));

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests = [
    [ ["SPM",  [],         [],            0 ], [0xe8, 0x95] ],
    [ ["SPM",  [null],     ["Z+"],        0 ], [0xf8, 0x95] ],
    [ ["ELPM", [],         [],            0 ], [0xd8, 0x95] ],
    [ ["ELPM", [12, 30],   ["R12", "Z"],  0 ], [0xc6, 0x90] ],
    [ ["ELPM", [12, 30],   ["R12", "Z"],  0 ], [0xc6, 0x90] ],
    [ ["ELPM", [13, null], ["R13", "Z+"], 0 ], [0xd7, 0x90] ],
    [ ["LPM",  [],         [],            0 ], [0xC8, 0x95] ],
    [ ["LPM",  [25, 30],   ["R25", "Z"],  0 ], [0x94, 0x91] ],
    [ ["LPM",  [26, null], ["R26", "Z+"], 0 ], [0xa5, 0x91] ]
];

for (const test of tests) {
    const source = test[0] as Instruction;
    const expected = test[1]!;
    const mnemonic = source[0]!;
    const symbolicOperands = source[2] as Array<string>;
    const operands = symbolicOperands.slice(1).join(", ");
    const description = operands ? operands : "no operands";
    Deno.test(`Basic code generation: ${mnemonic} with ${description}`, () => {
        assertEquals(littleEndian(generate(source)), expected);
    });
}

const failingTests = [
    ["SPM", [null], ["-X"], 0],
    ["SPM", [6],    ["6"],  0]
];

for (const test of failingTests) {
    const source = test as Instruction;
    const mnemonic = source[0];
    const operands = source[2].slice(1).join(", ");
    const description = operands ? operands : "no operands";
    Deno.test(`Bad syntax: ${mnemonic} with ${description}`, () => {
        assertThrows(
            () => generate(source),
            Error,
            "SPM can only have either no operands or Z+"
        );
    });
}
