import { assertThrows } from "assert";
import { createOurContext, theirContext } from "../context/mod.ts";
import { translator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";
import { operandConverter } from "../operands/mod.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["RCALL", ["back"   ]], [0xdf, 0xfc]],
    [["RJMP",  ["back"   ]], [0xcf, 0xfb]],
    [["RCALL", ["forward"]], [0xd0, 0x04]],
    [["RJMP",  ["forward"]], [0xc0, 0x03]]
];

const context = createOurContext(theirContext());
context.theirs.back = 0x00;
context.theirs.forward = 0x0a
context.programMemoryPos = 0x03;
testing(tests, context);

Deno.test("Absolute address too high on RJMP instruction", () => {
    context.programMemoryPos = 0;
    const translate = translator(context, operandConverter(context));
    assertThrows(
        () => translate(["RJMP", ["0x1111"]]),
        RangeError,
        "Operand out of range: should be relative jump to 12 bit range (-2048 - 2047) not 0x1111"
    );
});

Deno.test("Absolute address too low on RCALL instruction", () => {
    context.programMemoryPos = 0x2000;
    const translate = translator(context, operandConverter(context));
    assertThrows(
        () => translate(["RCALL", ["0x500"]]),
        RangeError,
        "Operand out of range: should be relative jump to 12 bit range (-2048 - 2047) not 0x500"
    );
});
