import { assertEquals } from "assert";
import { translator } from "../generate/mod.ts";
import { operandConverter } from "../operands/mod.ts";
import { type Tests, description} from "./testing.ts";
import { newContext } from "../context/context.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["ADIW", ["R26",  "5"]], [0x96, 0x15]],
    [["SBIW", ["R26", "57"]], [0x97, 0xd9]]
];

Deno.test("Word Immediate Code Generation", () => {
    newContext();
    const translate = translator(operandConverter());
    for (const test of tests) {
        assertEquals(translate(test[0]), test[1], description(test));
    }
});
