import { createOurContext } from "../context/mod.ts";
import { generator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [["", "ADIW", ["R26",  "5"]], [0x96, 0x15]],
    [["", "SBIW", ["R26", "57"]], [0x97, 0xd9]]
];

testing(tests, generator(createOurContext()));
