import { createOurContext } from "../context/mod.ts";
import { generator } from "../generate/mod.ts";
import { type Tests, testing } from "./testing.ts";

// The bytes for these tests were generated by the last version of GAVRAsm
// that I could get hold of.

const tests: Tests = [
    [
        ["", "ADIW", ["R26", "5"]],
        [0x15, 0x96]
    ],
    [
        ["", "SBIW", ["R26", "57"]],
        [0xd9, 0x97]
    ]
];

testing(tests, generator(createOurContext()));
